// Mocks generated by Mockito 5.4.6 from annotations
// in pmb_app/test/features/auth/presentation/bloc/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:flutter/material.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pmb_app/core/local_storage/shared_preferences/shared_preferences_helper.dart'
    as _i10;
import 'package:pmb_app/core/utils/failure.dart' as _i7;
import 'package:pmb_app/features/auth/data/models/login_request.dart' as _i9;
import 'package:pmb_app/features/auth/domain/entity/user_entity.dart' as _i8;
import 'package:pmb_app/features/auth/domain/repository/auth_repository.dart'
    as _i2;
import 'package:pmb_app/features/auth/domain/usecase/auth_usecase.dart' as _i5;
import 'package:shared_preferences/shared_preferences.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferences_2 extends _i1.SmartFake
    implements _i4.SharedPreferences {
  _FakeSharedPreferences_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthUsecase extends _i1.Mock implements _i5.AuthUsecase {
  MockAuthUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i8.UserEntity>> login(
    _i9.LoginRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue:
                _i6.Future<_i3.Either<_i7.Failure, _i8.UserEntity>>.value(
                  _FakeEither_1<_i7.Failure, _i8.UserEntity>(
                    this,
                    Invocation.method(#login, [request]),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, _i8.UserEntity>>);
}

/// A class which mocks [SharedPreferencesHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesHelper extends _i1.Mock
    implements _i10.SharedPreferencesHelper {
  MockSharedPreferencesHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SharedPreferences get pref =>
      (super.noSuchMethod(
            Invocation.getter(#pref),
            returnValue: _FakeSharedPreferences_2(
              this,
              Invocation.getter(#pref),
            ),
          )
          as _i4.SharedPreferences);

  @override
  _i6.Future<void> saveThemeMode(_i11.ThemeMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#saveThemeMode, [mode]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i11.ThemeMode getThemeMode() =>
      (super.noSuchMethod(
            Invocation.method(#getThemeMode, []),
            returnValue: _i11.ThemeMode.system,
          )
          as _i11.ThemeMode);

  @override
  _i6.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  bool isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<void> saveUserToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserToken, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveUserData(String? userDataInJson) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserData, [userDataInJson]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeUserData() =>
      (super.noSuchMethod(
            Invocation.method(#removeUserData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
